language: ruby
rvm:
  - 2.0.0
gemfile:
  - Gemfile.rails-4.0.1
  - Gemfile.rails-3.2.15
  - Gemfile.rails-3.1.12
  - Gemfile.rails-3.0.20
  - Gemfile.mongoid-3.1.5
  - Gemfile.mongoid-3.0.23
  - Gemfile.mongoid-2.7.1
  - Gemfile.mongoid-2.8.1
  - Gemfile.mongoid-2.6.0
  - Gemfile.mongoid-2.5.2
  - Gemfile.mongoid-2.4.12
env: DB=sqlite
services: mongodb
before_install:
  - gem uninstall json
  - gem install bundler
